// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace workKFC.Models;

public partial class customer
{
    [Key]
    [DisplayName("編號")]
    public int id { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    [DisplayName("帳號")]
    public string account { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    [DisplayName("密碼")]
    public string password { get; set; }

    [StringLength(30)]
    [DisplayName("姓名")]
    public string name { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    [DisplayName("電話")]
    public string tel { get; set; }

    [StringLength(50)]
    [DisplayName("地址")]
    public string address { get; set; }
}