// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace workKFC.Models;

public partial class meals
{
    [Key]
    [StringLength(5)]
    [Unicode(false)]
    [DisplayName("編號")]
    public string num { get; set; }

    [StringLength(50)]
    [DisplayName("餐點名稱")]
    public string title { get; set; }
    [DisplayName("價格")]
    public int? price { get; set; }

    [StringLength(30)]
    [DisplayName("圖片")]
    public string img { get; set; }
}