// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace workKFC.Models;

public partial class orders
{
    [Key]
    [DisplayName("編號")]
    public int id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    [DisplayName("訂單編號")]
    public string ordersnum { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    [DisplayName("帳號")]
    public string account { get; set; }
    [DisplayName("日期")]
    public DateTime? orderdate { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    [DisplayName("餐點編號")]
    public string mealnum { get; set; }

    [StringLength(50)]
    [DisplayName("餐點名稱")]
    public string mealtitle { get; set; }
    [DisplayName("數量")]
    public int? qty { get; set; }
    [DisplayName("單價")]
    public int? price { get; set; }
    [DisplayName("小計")]
    public int? total { get; set; }
}