// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace workKFC.Models;

public partial class workKFCContext : DbContext
{
    public workKFCContext(DbContextOptions<workKFCContext> options)
        : base(options)
    {
    }

    public workKFCContext()
    {

    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
            optionsBuilder.UseSqlServer("Server=.\\SQLExpress;Database=workKFC;Trusted_Connection=True;TrustServerCertificate=true;MultipleActiveResultSets=true;");
        }
    }

    public virtual DbSet<customer> customer { get; set; }

    public virtual DbSet<meals> meals { get; set; }

    public virtual DbSet<orders> orders { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<customer>(entity =>
        {
            entity.Property(e => e.tel).IsFixedLength();
        });

        modelBuilder.Entity<orders>(entity =>
        {
            entity.Property(e => e.id).ValueGeneratedOnAdd();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}